# (generated with --quick)

from typing import Any

api: Search
fire: module
t: Any

class Search(object):
    __doc__: str
    def platforms(self) -> Any: ...
    def project(self, manager: str, package: str) -> Any: ...
    def project_contributors(self, manager: str, package: str) -> Any: ...
    def project_dependencies(self, manager: str, package: str) -> Any: ...
    def project_dependent_repositories(self, manager: str, package: str) -> Any: ...
    def project_dependents(self, manager: str, package: str) -> Any: ...
    def project_search(self, **kwargs) -> Any: ...
    def project_sourcerank(self, manager: str, package: str) -> Any: ...
    def project_usage(selfself: Search, manager: str, package: str) -> Any: ...
    def repository(self, host: str, owner: str, repo: str) -> Any: ...
    def repository_dependencies(self, host: str, owner: str, repo: str) -> Any: ...
    def repository_projects(self, host: str, owner: str, repo: str) -> Any: ...
    def user(self, host: str, user: str) -> Any: ...
    def user_dependencies(self, host, user) -> Any: ...
    def user_packages(self, host: str, user: str) -> Any: ...
    def user_packages_contributions(self, host: str, user: str) -> Any: ...
    def user_repositories(self, host: str, user: str) -> Any: ...
    def user_repository_contributions(self, host: str, user: str) -> Any: ...

def search_api(action, *args, **kwargs) -> Any: ...
def set_pages(per_page = ..., page = ...) -> str: ...
